---
components:
  schemas:
    api_errors:
      description: ""
      properties:
        charge:
          description: For card errors, the ID of the failed charge.
          maxLength: 5000
          type: string
        code:
          description: For some errors that could be handled programmatically, a short
            string indicating the [error code](https://stripe.com/docs/error-codes)
            reported.
          maxLength: 5000
          type: string
        decline_code:
          description: For card errors resulting from a card issuer decline, a short
            string indicating the [card issuer's reason for the decline](https://stripe.com/docs/declines#issuer-declines)
            if they provide one.
          maxLength: 5000
          type: string
        doc_url:
          description: A URL to more information about the [error code](https://stripe.com/docs/error-codes)
            reported.
          maxLength: 5000
          type: string
        message:
          description: A human-readable message providing more details about the error.
            For card errors, these messages can be shown to your users.
          maxLength: 40000
          type: string
        param:
          description: If the error is parameter-specific, the parameter related to
            the error. For example, you can use this to display a message near the
            correct form field.
          maxLength: 5000
          type: string
        payment_intent:
          "$ref": "#/components/schemas/payment_intent"
        payment_method:
          "$ref": "#/components/schemas/payment_method"
        payment_method_type:
          description: If the error is specific to the type of payment method, the
            payment method type that had a problem. This field is only populated for
            invoice-related errors.
          maxLength: 5000
          type: string
        setup_intent:
          "$ref": "#/components/schemas/setup_intent"
        source:
          anyOf:
            - "$ref": "#/components/schemas/bank_account"
            - "$ref": "#/components/schemas/card"
            - "$ref": "#/components/schemas/source"
          description: The source object for errors returned on a request involving
            a source.
        type:
          description: The type of error returned. One of `api_connection_error`,
            `api_error`, `authentication_error`, `card_error`, `idempotency_error`,
            `invalid_request_error`, or `rate_limit_error`
          enum:
            - api_connection_error
            - api_error
            - authentication_error
            - card_error
            - idempotency_error
            - invalid_request_error
            - rate_limit_error
          type: string
      required:
        - type
      title: APIErrors
      type: object
      x-expandableFields:
        - payment_intent
        - payment_method
        - setup_intent
        - source
    error:
      description: An error response from the Stripe API
      properties:
        error:
          "$ref": "#/components/schemas/api_errors"
      required:
        - error
      type: object
openapi: 3.0.0
